### ISSUE TITLE
quest book

### ISSUE THREAD

**Issue by nutmegwand** [Dold1K/Regrowth-Minetest-Edition#1]
i completed a quest but i couldn't submit it

**Comment by Dold1K** [comment]
Hey, you probably confused repository

**Comment by nutmegwand** [comment]
> Hey, you probably confused repository

i don't understand

**Comment by Dold1K** [comment]
Erm. My rep is empty. I abandoned it

**Comment by nutmegwand** [comment]
> Erm. My rep is empty. I abandoned it

so what you are saying is you abandoned the mod?

**Comment by Dold1K** [comment]
Something like that, but mb in future i will begin again develop it
